deploy:
  provider: heroku
  api_key:
    secure: DYffGDiOrGewaepVf6B57jknJpybV6O4DviInmOe9lWMPUPpQIbS/W+KczXffWMYPoO5VhaMdtOweJudTXOBm/UCwjVhQ908pECgzDiFrzV31EwMoEw+qV0CC8WaH7hWynarfbYKH3Uv492T2uS5o+Rng33I008DXNji8WurO/U=
  app: feedme-c
  on:
    repo: netguru-training/feedme
