before_script:
  - cp config/database.yml.sample config/database.yml
  - psql -c 'create database feedme_test;' -U postgres
deploy:
  provider: heroku
  api_key:
    secure: <%= ENV.fetch('travis_api_key') %>
  app: feedme-c
  on:
    repo: netguru-training/feedme
