before_script:
  - cp config/database.yml.sample config/database.yml
deploy:
  provider: heroku
  api_key:
    secure: <%= Settings.travis_api_key %>
  app: feedme-c
  on:
    repo: netguru-training/feedme