travis_api_key: DYffGDiOrGewaepVf6B57jknJpybV6O4DviInmOe9lWMPUPpQIbS/W+KczXffWMYPoO5VhaMdtOweJudTXOBm/UCwjVhQ908pECgzDiFrzV31EwMoEw+qV0CC8WaH7hWynarfbYKH3Uv492T2uS5o+Rng33I008DXNji8WurO/U=
mailgun_domain: sandboxaf40cd7a2fbe408081b4e2ff2bfc3090.mailgun.org
mailgun_user_name: postmaster@sandboxaf40cd7a2fbe408081b4e2ff2bfc3090.mailgun.org
mailgun_password: 02180331be48c53be5016736ebe59563